### ISSUE TITLE
[1] Create application template

### ISSUE THREAD

**Issue by JaroslawPalasz** [JaroslawPalasz/TCalculator#1]
Create functional application template as below:

- [x]  `Calculation `class;

- `calculate `method for various type of arguments like String(s), Double(s), String..., Double... etc.;

_`toString()` method that prints calculation as: var1 sign var2 result f.eg. 2.0 + 2.0 = 4.0 or 2.0 + 3.0, 2.0 + Na;_

- [x]  Classes for all calculation types in type of Calculation;

- implementation of each calculation types methods.

_`toString()` method that prints calculation as: var1 sign var2 result f.eg. 2.0 + 2.0 = 4.0 or 2.0 + 3.0, 2.0 + Na;_

_`DividedByZeroException `exception class;_

_Moved to other tasks._

**Comment by JaRutkowski** [comment]
Done.
